// <auto-generated />
using System;
using Chubberino.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chubberino.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210415231732_AddEmote")]
    partial class AddEmote
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chubberino.Database.Models.ApplicationCredentials", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InitialTwitchPrimaryChannelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitchAPIClientID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WolframAlphaAppID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ApplicationCredentials");
                });

            modelBuilder.Entity("Chubberino.Database.Models.Boss", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("Chubberino.Database.Models.Emote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("TwitchUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Emotes");
                });

            modelBuilder.Entity("Chubberino.Database.Models.StartupChannel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StartupChannels");
                });

            modelBuilder.Entity("Chubberino.Database.Models.UserCredentials", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBot")
                        .HasColumnType("bit");

                    b.Property<string>("TwitchUsername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Chubberino.Modules.CheeseGame.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatCount")
                        .HasColumnType("int");

                    b.Property<int>("CheeseUnlocked")
                        .HasColumnType("int");

                    b.Property<int>("ContributedDamageToBoss")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastHeistInitiated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPointsGained")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastQuestVentured")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaximumPointStorage")
                        .HasColumnType("int");

                    b.Property<int>("MouseCount")
                        .HasColumnType("int");

                    b.Property<int>("MouseTrapCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NextCheeseModifierUpgradeUnlock")
                        .HasColumnType("int");

                    b.Property<int>("NextCriticalCheeseUpgradeUnlock")
                        .HasColumnType("int");

                    b.Property<int>("NextQuestRewardUpgradeUnlock")
                        .HasColumnType("int");

                    b.Property<int>("NextStorageUpgradeUnlock")
                        .HasColumnType("int");

                    b.Property<int>("NextWorkerProductionUpgradeUnlock")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("PopulationCount")
                        .HasColumnType("int");

                    b.Property<int>("Prestige")
                        .HasColumnType("int");

                    b.Property<int>("QuestsUnlockedCount")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("TwitchUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
