name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        bash ./move_resx.sh
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        bash ./move_resx.sh
        dotnet test --no-restore --verbosity normal
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-with-all
        path: |
          ./bin/Release/netcoreapp3.1
